config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#main'
  resources :pages
  # resources :blog_posts
  resources :users

  get '/blog_posts', to: 'blog_posts#index', as: 'blog_posts'
  get '/blog_posts/new', to: 'blog_posts#new', as: 'new_blog_post'
  post '/blog_posts/', to: 'blog_posts#create'
  get '/blog_posts/:id/edit', to: 'blog_posts#edit', as: 'edit_blog_post'
  get '/blog_posts/:id', to: 'blog_posts#show', as: 'blog_post'
  patch '/blog_posts', to: 'blog_posts#update'
  put '/blog_posts', to: 'blog_posts#update'
  post '/blog_posts/:id', to: 'blog_posts#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  def index
    @blog_posts = ::BlogPost.all
  end

  def show
    @blog_post = BlogPost.find(params[:id])
  end

  def new
    @blog_post = ::BlogPost.new
  end

  def create
    require 'pry'
    binding.pry
    @blog_post = ::BlogPost.new(blog_post_params)
    if @blog_post.valid?
      @blog_post.save
      redirect_to @blog_post
    else
      render 'new'
    end
  end

  def edit
    @blog_post = ::BlogPost.find(params[:id])
  end

  def update
    require 'pry'
    binding.pry
    @blog_post = ::BlogPost.find(params[:id])
    if @blog_post.valid?
      @blog_post.update_attributes(blog_post_params)
      redirect_to @blog_post
    else
      render 'edit'
    end
  end

  def destroy
    ::BlogPost.find(params[:id]).destroy
    flash[:success] = "BlogPost deleted"
    redirect_to blogposts_path
  end

  private

  def blog_post_params
    params.required(:blog_post)
      .permit(:title,
              :summary,
              :content,
              :user_id,
              :title_image_url)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = ::User.all
  end

  def show
    @user = ::User.find(params[:id])
  end

  def new
    @user = ::User.new(is_admin: false)
  end

  def create
    @user = ::User.new(user_params)
    if @user.valid?
      @user.save
      redirect_to users_url
    else
      render 'new'
    end
  end

  def edit
    @user = ::User.find(params[:id])
  end

  def update
    @user = ::User.find(params[:id])
    if @user.valid?
      @user.update_attributes(user_params)
      redirect_to users_url(@user)
    else
      render 'edit'
    end
  end

  def destroy
    ::User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_path
  end

  private

  def user_params
    params.required(:user)
      .permit(:name,
              :email,
              :is_admin,
              :password,
              :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
    <div class="form-group">
      <%= f.text_field :title, placeholder: "Title", size: "50", class: 'form-control' %>
      <%= f.text_field :summary, placeholder: "Summary", size: "100", class: 'form-control' %>
      <%= f.text_field :content, placeholder: "Content", size: "200", class: 'form-control' %>
      <%= f.text_field :user_id, placeholder: "User ID", size: "50", class: 'form-control' %>
      <%= f.text_field :title_image_url, placeholder: "Title Image URL", size: "50", class: 'form-control' %>
      <%= f.submit "Submit", class:"btn btn-default" %>
    </div>
<%end%>

app/views/blog_posts/edit.html.erb
<%= render 'form' %>

app/views/blog_posts/index.html.erb
<a class="btn btn-primary" href="<%= new_blog_post_path %>">Add New Blog</a>

<table class="table table-bordered">
  <thead class="bg-info">
    <tr>
      <th>Title</th>
      <th>Summary</th>
      <th>User ID</th>
      <th colspan="2">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @blog_posts.each do |blog_post| %>
    <tr>
      <td>
        <a class="btn btn-info" href="<%= blog_post_path(blog_post.id) %>"><%=blog_post.title%></a>
      </td>
      <td>
        <%=blog_post.summary%>
      </td>
      <td>
        <%=blog_post.user_id%>
      </td>
      <td>
        <a class="btn btn-warning" href="<%=edit_blog_post_path(blog_post.id)%>">Edit</a>
      </td>
      <td>
        <%= button_to "Delete", blog_post, method: :delete,
                                  data: { confirm: "You sure?" },
                                  class: "btn btn-danger" %>
      </td>
    </tr>
  </tbody>
  <%end%>
</table>

app/views/blog_posts/new.html.erb
<%= render 'form' %>

app/views/blog_posts/show.html.erb
<a class="btn btn-primary" href="<%= blog_posts_path %>">Back</a>

<table class="table table-bordered">
  <tbody>
    <tr>
      <td class="bg-info">Title</td>
      <td><%= @blog_post.title %></td>
    </tr>
    <tr>
      <td class="bg-info">Summary</td>
      <td><%= @blog_post.summary %></td>
    </tr>
    <tr>
      <td class="bg-info">Content</td>
      <td><%= @blog_post.content %></td>
    </tr>
    <tr>
      <td class="bg-info">User ID</td>
      <td><%= @blog_post.user_id %></td>
    </tr>
    <tr>
      <td class="bg-info">Title Image URL</td>
      <td><%= @blog_post.title_image_url %></td>
    </tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Clean Blog - Start Bootstrap Theme</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="index.html">Start Bootstrap</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="index.html">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="about.html">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="post.html">Sample Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="contact.html">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Header -->
    <header class="masthead" style="background-image: url('<%= image_url 'home-bg.jpg'%>')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>Clean Blog</h1>
              <span class="subheading">A Blog Theme by Start Bootstrap</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10">
          <%= yield %>
        </div>
      </div>
    </div>


    <hr>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; Your Website 2018</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
  <%= javascript_include_tag 'application' %>
</html>

app/views/pages/main.html.erb
    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-preview">
            <a href="post.html">
              <h2 class="post-title">
                Man must explore, and this is exploration at its greatest
              </h2>
              <h3 class="post-subtitle">
                Problems look mighty small from 150 miles up
              </h3>
            </a>
            <p class="post-meta">Posted by
              <a href="#">Start Bootstrap</a>
              on September 24, 2018</p>
          </div>
          <hr>
          <div class="post-preview">
            <a href="post.html">
              <h2 class="post-title">
                I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.
              </h2>
            </a>
            <p class="post-meta">Posted by
              <a href="#">Start Bootstrap</a>
              on September 18, 2018</p>
          </div>
          <hr>
          <div class="post-preview">
            <a href="post.html">
              <h2 class="post-title">
                Science has not yet mastered prophecy
              </h2>
              <h3 class="post-subtitle">
                We predict too much for the next year and yet far too little for the next ten.
              </h3>
            </a>
            <p class="post-meta">Posted by
              <a href="#">Start Bootstrap</a>
              on August 24, 2018</p>
          </div>
          <hr>
          <div class="post-preview">
            <a href="post.html">
              <h2 class="post-title">
                Failure is not an option
              </h2>
              <h3 class="post-subtitle">
                Many say exploration is part of our destiny, but it’s actually our duty to future generations.
              </h3>
            </a>
            <p class="post-meta">Posted by
              <a href="#">Start Bootstrap</a>
              on July 8, 2018</p>
          </div>
          <hr>
          <!-- Pager -->
          <div class="clearfix">
            <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
          </div>
        </div>
      </div>
    </div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="row control-group">
    <div class="form-group">
      <%= f.text_field :name, placeholder: "Name", size: "50", class: 'form-control' %>
      <%= f.text_field :email, placeholder: "Email", size: "50", class: 'form-control' %>
      <%= f.password_field :password, placeholder: "Password", size: "50", class: 'form-control' %>
      <%= f.password_field :password_confirmation, placeholder: "Password Confirmation", size: "50", class: 'form-control' %>
      <%= f.check_box :is_admin, class: 'form-control' %>
      <%= f.submit "Submit", class:"btn btn-default" %>
    </div>
  </div>
<%end%>

app/views/users/index.html.erb
<a class="btn btn-primary" href="<%= new_user_path %>">Add New User</a>

<table class="table table-bordered">
  <thead class="bg-info">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Is Admin?</th>
      <th colspan="2">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td>
        <a class="btn btn-info" href="<%= user_path(user.id) %>"><%=user.name%></a>
      </td>
      <td>
        <%=user.email%>
      </td>
      <td>
        <%=user.password_digest%>
      </td>
      <td>
        <%=user.is_admin%>
      </td>
      <td>
        <a class="btn btn-warning" href="<%=edit_user_path(user.id)%>">Edit</a>
      </td>
      <td>
        <%= button_to 'Destroy',
            user,
            method: :delete,
            class: 'btn btn-danger',
            data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  </tbody>
  <%end%>
</table>

app/views/users/show.html.erb
<ul class="list-inline">
<li><a class="btn btn-primary" href="<%= users_path %>">Back</a></li>
<li><%= button_to 'Delete',
            user_path(@user.id),
            method: :delete,
            class: 'btn btn-danger' %></li>
</ul>

<table class="table table-bordered">
  <tbody>
    <tr>
      <td class="bg-info">Name</td>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <td class="bg-info">Email</td>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <td class="bg-info">Password</td>
      <td><%= @user.password_digest %></td>
    </tr>
    <tr>
      <td class="bg-info">Is Admin</td>
      <td><%= @user.is_admin %></td>
    </tr>
  </tbody>
</table>